# Generated by Django 4.2.4 on 2023-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_body',
            field=models.CharField(max_length=1000000),
        ),
    ]
