# Generated by Django 4.2.4 on 2023-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logingAPI', '0008_user_delete_userprofile'),
        ('backend', '0002_alter_story_story_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='liked_by',
            field=models.ManyToManyField(default=None, to='logingAPI.user'),
        ),
        migrations.AlterField(
            model_name='story',
            name='liked_by',
            field=models.ManyToManyField(default=None, to='logingAPI.user'),
        ),
    ]
