# Generated by Django 4.2.4 on 2023-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logingAPI', '0005_userprofile_bio_userprofile_city_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
