# Generated by Django 4.2.4 on 2023-08-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logingAPI', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='address',
        ),
    ]
