# Generated by Django 4.2.4 on 2023-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logingAPI', '0009_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imgage',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
