# Generated by Django 4.2.4 on 2023-08-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logingAPI', '0010_userprofile_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='imgage',
            new_name='image',
        ),
    ]
